#!/bin/sh

### BEGIN INIT INFO
# Provides:          example
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts a service for the Sparked plugin 'example'
# Description:       Generic plugin starter for sparkd plugins
### END INIT INFO
# Author: Arjan Scherpenisse <arjan@scherpenisse.net>

APPLICATION="example"

. /usr/share/sparked/sparked-init
