#!/bin/sh

APPLICATION="${0##*/}"

### BEGIN INIT INFO
# Provides:          $APPLICATION
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts a service for the Sparked plugin '$APPLICATION'
# Description:       Generic plugin starter for sparkd plugins
### END INIT INFO
# Author: Arjan Scherpenisse <arjan@scherpenisse.net>

UID=nobody
GID=nogroup
PIDFILE=/var/run/$APPLICATION.pid
LOGFILE=/var/log/$APPLICATION.log
OPTIONS=""

if [ -f /etc/default/$APPLICATION ]; then
    source /etc/default/$APPLICATION
fi

touch $LOGFILE && chown $UID:$GID $LOGFILE

DAEMON=/usr/bin/twistd
DAEMON_OPTS="--pidfile $PIDFILE --uid $UID --gid $GID sparked -s $APPLICATION $OPTIONS"

DB=/var/lib/$APPLICATION
mkdir -p $DB && chown -R $UID:$GID $DB

if [ ! -x $DAEMON ]; then
  echo "ERROR: Can't execute $DAEMON."
  exit 1
fi

start_service() {
  echo -n " * Starting $APPLICATION... "
  start-stop-daemon -Sq -p $PIDFILE -x $DAEMON -- $DAEMON_OPTS
  e=$?
  if [ $e -eq 1 ]; then
    echo "already running"
    return
  fi

  if [ $e -eq 255 ]; then
    echo "couldn't start :("
    return
  fi

  echo "done"
}

stop_service() {
  echo -n " * Stopping $APPLICATION... "
  start-stop-daemon -Kq -R 10 -p $PIDFILE
  e=$?
  if [ $e -eq 1 ]; then
    echo "not running"
    return
  fi
  rm -f $PIDFILE
  echo "done"
}

reload_service() {
  echo -n " * Reloading $APPLICATION... "
  start-stop-daemon -Kq -p $PIDFILE -s USR1 # rotate logs
  start-stop-daemon -Kq -p $PIDFILE -s USR2 # loadService() call in sparked Application
  e=$?
  if [ $e -eq 1 ]; then
    echo "not running"
    return
  fi

  echo "done"
}

case "$1" in
  start)
    start_service
    ;;
  stop)
    stop_service
    ;;
  restart)
    stop_service
    start_service
    ;;
  force-reload|reload)
    reload_service
    ;;
  *)
    echo "Usage: /etc/init.d/$APPLICATION {start|stop|restart}" >&2
    exit 1
    ;;
esac

exit 0